apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-nodeselector-pod
  labels:
    name: kubernetes-nodeselector-pod
spec:
  containers:
  - name: kubernetes-nodeselector-pod
    image: arisu1000/simple-container-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  nodeSelector:
    disktype: ssd
