apiVersion: v1
kind: Pod
metadata:
  name: post-start-hook
  labels:
    name: post-start-hook
spec:
  containers:
  - name: post-start-hook
    image: k8spatterns/random-generator:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    lifecycle:
      postStart:
        exec:
          command:
            - sh
            - -c
            - sleep 30 && echo "wake up!" > /tmp/postStart_done
