apiVersion: v1
kind: Pod
metadata:
  name: pre-stop-hook
  labels:
    name: pre-stop-hook
spec:
  containers:
  - name: pre-stop-hook
    image: k8spatterns/random-generator:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    lifecycle:
      preStop:
        httpGet:
          port: 8080
          path: /shutdown
