apiVersion: v1
kind: Pod
metadata:
  name: random-generator
  labels:
    name: random-generator
spec:
  containers:
  - name: random-generator
    image: k8spatterns/random-generator:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  nodeSelector:
    diskType: ssd # diskType: ssd 라고 설정된 레이블을 가진 노드만이 생성 가능 
