apiVersion: batch/v1
kind: Job
metadata:
  name: random-generator
spec:
  ttlSecondsAfterFinished: 100
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: OnFailure
