apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-nodeaffinity-pod
  labels:
    name: kubernetes-nodeaffinity-pod
spec:
  containers:
  - name: kubernetes-nodeaffinity-pod
    image: arisu1000/simple-container-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
              - window
            - key: disktype
              operator: Exists
            - key: core # 코어가 4개이상일때만 스케줄링
              operator: Gt
              values:
                - "4"
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 10 # 키에 해당하는 조건이 맞을때 10점을 부여하고 이닐경우에 0 토탈합이 가장높은 노드를 선택 
          preference:
            matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - worker-node01

