apiVersion: v1
kind: Pod
metadata:
  name: pod-with-liveness-check
  labels:
    name: pod-with-liveness-check
spec:
  containers:
  - name: pod-with-liveness-check
    image: k8spatterns/random-generator:1.0
    env:
      - name: DELAY_STARTUP
        value: "20"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /actuator/health
        port: 8080
      initialDelaySeconds: 30 # 애플리케이션의 준비시간을 주기위해서 라이브니스 점검수행을 30초 딜레이줌.
